version: "3.9"

services:

  # Backend API
  facerecog-api-docker:
    container_name: backend
    # image: node:14.17.5
    build: ./
    command: npm start
    working_dir: /usr/src/facerecog-api
    environment:
      POSTGRES_URI: postgres://fx:admin@postgres:5432/facerecog-db-docker
    links:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/facerecog-api

  # Postgres:
  postgres:
    environment:
      POSTGRES_USER: fx
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: facerecog-db-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

