version: "3.9"

services:
  facerecog-api-docker:
    container_name: backend
    # image: node:14.17.5
    build: ./
    command: npm start
    working_dir: /usr/src/facerecog-api
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/facerecog-api