version: "3.9"

services:

  # Backend API
  backend:
    build: ./
    command: npm run dev
    working_dir: /usr/src/facerecog-api
    environment:
      POSTGRES_URI: postgres://fx:admin@postgres:5432/facerecog-db-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/facerecog-api

  # Postgres:
  postgres:
    environment:
      POSTGRES_USER: fx
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: facerecog-db-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
  
  # Redis    
  redis:
    image: "redis"
    ports: 
      - "6379:6379"

